#!/usr/bin/env node
// timeline.js: turn the output generated by time_list.js into json
//              that can be loaded into a Chrome timeline
//
// Usage:
//     timeline.js <log file name> > timeline-loadable.json
//

/* jslint node:true */

var logfilename = process.argv[2] || 'log';
var fs = require('fs');
var str = fs.readFileSync(logfilename, 'utf8');
var items = JSON.parse('[' + str + ' {} ]');

console.log("[");
console.log('"Mozilla/5.0 (iPad; CPU OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B554a Safari/9537.53"');
for (var i = 0; i < items.length; i++) {
    var item = items[i];
    if (item['0'] === "recv") {
        var d0 = JSON.parse(item['1']);
        if (d0.method === 'Timeline.eventRecorded') {
            var r = d0.params.record;
            console.log(", " + JSON.stringify(r, null, 2));
        }
    }
}

console.log("]");

